service: server-cainsi-app
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: sa-east-1
  iamRoleStatements:
    - Effect: Allow
      Action: lambda:InvokeFunction
      Resource: "*"

functions:
  serverApp:
    handler: src/api/server.serverApp
    events:
      - http:
          method: POST
          path: /receive-json
